name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  libretro-prboom:
    runs-on: ubuntu-latest
    container: fjtrujy/ps2dev:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base git bash
    

    - name: Compile project
      run: |
        ./prepare_release.sh
        ./prepare_retroarch.sh
        ./libretro-prboom.sh
        ./generate_retroarch.sh libretro-prboom prboom_libretro_ps2

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: RA
        path: RA/
  

  libretro-samples:
    runs-on: ubuntu-latest
    container: fjtrujy/ps2dev:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base git bash
    
    - name: Compile project
      run: |
        ./prepare_release.sh
        ./prepare_retroarch.sh
        ./libretro-samples.sh
        ./generate_retroarch.sh libretro-samples test_libretro_ps2

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: RA
        path: RA/
    

  libretro-salamander:
    runs-on: ubuntu-latest
    container: fjtrujy/ps2dev:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base git bash
    
    - name: Compile project
      run: |
        ./prepare_release.sh
        ./prepare_retroarch.sh
        ./generate_salamander.sh

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: RA
        path: RA/


  libretro-info-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Compile project
      run: |
        ./prepare_release.sh
        ./libretro-core-info.sh

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: RA
        path: RA/

    